name: 'jira-release-action'
description: 'Create or Update a Jira release'
author: 'Nicolas Charpentier, I-DNA Team'
inputs:
  jira_email:
    required: true
    description: Email address associated with api token
  jira_api_token:
    required: true
    description: Jira API token
  jira_base_url:
    required: true
    description: Jira API base URL
  jira_project:
    required: true
    description: Name of the JIRA project
  jira_issue_filter:
    description: Boolean JQL expression to identify suitable issues
    required: false
  jira_version_prefix:
    description: Prefix for release names on JIRA
    required: false
  github_api_token:
    required: true
    description: GitHub API token (PAT)
  github_org:
    required: true
    description: GitHub repository owner
  github_repo:
    required: true
    description: GitHub repository name
  dry_run:
    description: Query GitHub and Jira, but do not perform any updates.
    required: false
    default: 'false'

runs:
  using: 'node12'
  main: 'dist/index.js'
